


version: '3'

services:

  # Frontend Service (React)
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
      #this volume is used inorder to desplay the last updates in the browsers
    volumes:
      - ./frontend:/app
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      - REACT_APP_API_URL= http://backend:5000
    depends_on:
      - backend
    
  
# Backend Service (Express.js)
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app 
     
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: always
    environment:
      
       - MONGO_URI=mongodb+srv://gebeyehu123:geba@songs.cfxod.mongodb.net/?retryWrites=true&w=majority&appName=songs
   